### PR TITLE
Add new command to report on-screen color (color picker)

### PR DESCRIPTION
**Pull request by wfaulk**
In using cliclick to automate things, I sometimes find that I need to determine what's on the screen, and the simplest form of that is reporting the color of a particular pixel.

I've implemented a command, "cp" (for Color Picker), that reports the RGBA values of any pixel on screen, using the same point referencing as the other cliclick commands.

I specifically didn't implement a default location, as the default location would be the mouse pointer, which is likely to just report the color of the pointer itself.  If you really want that point, you can reference it explicitly: `cp:+0,+0`.

### CODE REVIEW

**Comment by BlueM** [comment]
Thanks, work nicely. (And someone in fact asked me for reading colours a while ago!)

There are only two things that could be changed (but probably I’m nitpicking). The one is the term “color picker”. This is without doubt the correct term, but most other actions (with the exception of “key press” and “key up”) are verbs, not nouns, and therefore I’m wondering if I like “pick colour” AKA “pc” better – or “read colour” or whatever. (Am not sure yet.) The other thing is that I would have expected the components of the colour to be separated by commas, not by spaces.

What do you think?

**Comment by wfaulk** [comment]
I'm indifferent to the shortcut.  If you like 'pc' or something else better, that's fine by me.

The reason I used spaces (and, incidentally, decimal numbers) was to make it easier to parse in Bourne/Korn shells.  For Korn shells (ksh, zsh), you'd be able to do `cliclick cp:123,456 | read r g b a`.  In Bourne shells (sh, ash, dash, bash), you can do ``set -- `cliclick cp:123,456` ``and have the values appear in $1–$4.  You could still do this with commas by redefining `$IFS` to hold `,`, but it seems more natural to just use the regular delimiter of the space.

That said, I understand why you'd want to use commas, since that's what you're using to delimit xy coordinates.

If you make a decision, let me know and I'll update the pull request.  Or you can modify it after accepting.  Or whatever you like.

**Comment by BlueM** [comment]
As “color picker” is the established term, it’s probably better to leave it as it is, despite what I’ve written earlier.

Regarding the spaces: valid argumentation. And of course: it is arguable why it might be better to use commas for consistency, when otherwise commas are used for coordinates, but color values or obviously *not* coordinates.

Later, one thing came to my mind, which is: won’t the Alpha value *always* be 255 (or 100%)? An Alpha value is important when composing an image/color, but when reading a color, I’d expect to always get a fully opaque color, as screen pixels show the result of all layered (possibly having an Alpha < 100%) and don’t have a notion of transparency. I just tried it out using an application wich lets me paint on the screen with a non-opaque color, and I got 255 as Alpha value, as (of course) the color I picked was a combination of the non-opaque red which I used for painting and the color behind it. Also, when picking a color using the system’s “Digital Color Meter” utility, there is no such thing like an Alpha value. So, to conclude: have you managed to get something else than 255 when testing?

Finally, there’s one thing I would love to have added, which is being able to use “.” as the current mouse position, which (this time: really) would be more consistent with other actions which offer to use “.” instead of coordinates. You can find code for that in `MouseBaseAction.m`.

Thanks.

**Comment by wfaulk** [comment]
I can't think how alpha could ever be anything other than 1.0/255/opaque.  I've removed it.

And I've got `cp:.` working, albeit a little differently than how you implemented it in `MouseBaseAction.m`.  I hope that's okay.

**Pull request merged**
