### PR TITLE
Remove ActionClassesMacro.h as it gets generated

### PR DESCRIPTION
**Pull request by muellermartin**
The file ActionClassesMacro.h is automatically generated in a "Run
Script" build phase of Xcode. Therefore there is no need to include it
in the repository.
To prevent this file getting added in a future commit, it is also added
to the patterns listed in the .gitignore.

### CODE REVIEW

**Comment by muellermartin** [comment]
The motivation behind this is related to PR #42 (adding a new action), because on each new added action a new line gets included in the file ActionClassesMacro.h which will get marked as modified in Git. I could have just added this change to the commit, but in my opionion this is somewhat useless as the file gets automatically generated.

**Comment by BlueM** [comment]
Yes, the file is automatically generated – but this is just a convenience for Xcode users. Actually, Xcode is not required to build cliclick, as one can also simply use `make` (using the provided `Makefile`), and in that case the file is not auto-generated, but still required for building.

**Comment by muellermartin** [comment]
Okay, then we could also include the one liner in the Makefile. Should I update the Makefile then or do you generally dislike this idea?

**Comment by muellermartin** [comment]
I've updated the branch [remove-generated-header](/muellermartin/cliclick/tree/remove-generated-header) to reflect this issue.

**Comment by muellermartin** [comment]
Thanks for merging :)

**Pull request merged**
