### PR TITLE
Implement scrolling

### PR DESCRIPTION
**Pull request by wfaulk**

### CODE REVIEW

**Comment by BlueM** [comment]
Very nice, thanks. [You acquired a taste for contributing to cliclick, right? :-) ]

There is only one thing with which I’m not quite happy, and that’s the interpretation of the given value:
“Positive is up/left; negative is down/right”
Given that coordinate 0,0 is the top left corner and doing something like `cliclick m:+100,+100` moves the mouse pointer to the right and down, I would have definitely expected the scrolling values to be interpreted in the opposite direction, i.e.: positive is down/right, negative is up/left.

**Comment by wfaulk** [comment]
I don't know what to tell you.  I'm pretty much just passing the values provided on the command line to `CGEventCreateScrollWheelEvent()`.  It's pretty easy to flip them around, but does it make sense to second-guess Apple?  Besides, as Apple proved when then changed trackpad scrolling behavior, scrolling direction is a matter of perception.

**Comment by BlueM** [comment]
I don’t think it’s second-guessing and I don’t claim that the way Apple interprets the arguments to `CGEventCreateScrollWheelEvent()` is inappropriate.
It’s simply a matter of consistency regarding how cliclick’s commands behave. Any of the existing commands that takes coordinates interprets larger numbers as more right / further down than smaller numbers (be it relative or absolute), and if scrolling behaved differently, that would be a pity.

If that change would be OK with you, I could of course merge your PR and inverse the scrolling direction myself. But I wouldn’t want to do that if you object.

**Comment by wfaulk** [comment]
Done.

**Comment by BlueM** [comment]
Thanks.

**Comment by BlueM** [comment]
While preparing for the next release, I did a little more testing, and found two issues I hadn’t noticed before:

1. When passing 2 values (such as `sl:10,10`), the second one seems to be ignored (on my primary Mac, running 10.10.5). However, the second one *does* work if the first value is 0, so the values are obviously passed correctly to Apple’s API. (And the same problem can be observed when directly hardcoding value into the source.) This is surprising, as from the documentation, this should work, and there is code on the web which does exactly what your code does. Does that work for you?

2. I didn’t manage to get the “3rd-dimension scrolling” to work – which I hadn’t tested at all before. I tried it with Google Maps in the browser, which I expected to scroll in or out (which works when I scroll on the trackpad). Even with `sp:0,0,10`, nothing happens. Did this work for you, and if yes: which application(s) did you use for testing?

The first issue could of course be fixed by sending separate events for X and Y (although I would like to understand why it doesn’t work with the current code), but regarding the second one I wouldn’t know what measure to take.

**Comment by wfaulk** [comment]
Crap.  Because I'm on a new computer and I didn't set my email address correctly in git.

**Comment by BlueM** [comment]
Regarding my 2nd comment (Sep 12) above: forget it. Of course Maps does not use the 3rd scrolling dimension.

However, regarding my first comment: I’ve done some testing following different approaches in code (scrolling 3 directions at once, like in your original code, vs. emitting 1–3 distinct events for only a single direction) and found that it is not reliably – for whatever reason. Sometimes I invoked something like `sp:20,20` three times, and the first two times, the window would scroll vertically, but not horizontally, while the third time, everything worked as expected. Moreoever, I experimented with inserting small delays to prevent too frequent events, but that didn’t help much. (For the record: I don’t think there’s anything wrong with your code. It must be something else.)

Did/do you encounter similar problems? I.e.: when performing the same scroll action 5 or 10 times, do you always get exactly the same behavior?

**Comment by brandonros** [comment]
Did `sl` scrolling get reverted?

**Comment by BlueM** [comment]
@brandonros: yes, see https://github.com/BlueM/cliclick/commit/d0bdfbc

**Pull request merged**
